import {
  BriefcaseBusiness,
  Check,
  CircleDot,
  ClipboardCheck,
  CreditCard,
  FileBarChart,
  FileText,
  LayoutDashboard,
  Users,
} from 'lucide-react';
import type { Job, JobStatus, NavGroup, Officer, Payment, RequestRow, RouteKey } from './types';

export const TODAY = '2026-07-09';

export const officers: Officer[] = [
  { id: 'OF-01', name: 'Rajesh Kumar', phone: '+65 8123 4501', status: 'Active', ic: true, rate: 16, jobsCount: 22 },
  { id: 'OF-02', name: 'Muhammad Faizal', phone: '+65 9223 8812', status: 'Active', ic: true, rate: 15, jobsCount: 18 },
  { id: 'OF-03', name: 'Tan Wei Ming', phone: '+65 8773 6611', status: 'Active', ic: true, rate: 18, jobsCount: 31 },
  { id: 'OF-04', name: 'Nur Aisyah', phone: '+65 9088 1142', status: 'New', ic: false, rate: 16, jobsCount: 0 },
  { id: 'OF-05', name: 'Lim Jun Hao', phone: '+65 8511 4429', status: 'Active', ic: true, rate: 17, jobsCount: 26 },
  { id: 'OF-08', name: 'Deepak Raj', phone: '+65 8990 7720', status: 'Blocked', ic: true, rate: 19, jobsCount: 11 },
];

export const jobs: Job[] = [
  {
    id: 'PN-2041',
    customer: 'Changi Airport Group',
    location: 'Jewel Changi - Canopy Park',
    date: TODAY,
    start: '08:00',
    end: '20:00',
    required: 6,
    status: 'Ongoing',
    posted: true,
    description: 'School holiday crowd control and access checks.',
    instructions: 'Hourly photo proof. Report to terminal ops desk.',
    officers: [
      { oid: 'OF-01', name: 'Rajesh Kumar', ic: 'Yes', rate: 16, confirmed: true, onDuty: true, actualStart: '08:00', actualEnd: '' },
      { oid: 'OF-02', name: 'Muhammad Faizal', ic: 'Yes', rate: 15, confirmed: true, onDuty: true, actualStart: '08:02', actualEnd: '' },
      { oid: 'OF-03', name: 'Tan Wei Ming', ic: 'Yes', rate: 18, confirmed: true, onDuty: true, actualStart: '08:01', actualEnd: '' },
      { oid: 'OF-05', name: 'Lim Jun Hao', ic: 'Yes', rate: 17, confirmed: true, onDuty: true, actualStart: '08:04', actualEnd: '' },
    ],
    photos: [
      { time: '09:00', status: 'received', by: 'Rajesh Kumar', at: '09:02' },
      { time: '10:00', status: 'received', by: 'Muhammad Faizal', at: '10:01' },
      { time: '11:00', status: 'missing', note: 'Reminder sent to WhatsApp group' },
      { time: '12:00', status: 'upcoming' },
    ],
    billing: 'Not Billed',
    invoice: '',
    billedDate: '',
  },
  {
    id: 'PN-2042',
    customer: 'OCBC Centre',
    location: 'OCBC Centre - Lobby',
    date: TODAY,
    start: '09:00',
    end: '18:00',
    required: 3,
    status: 'Waiting for Officers',
    posted: true,
    description: 'Lobby access control for tenant event.',
    instructions: 'Corporate attire.',
    officers: [{ oid: 'OF-04', name: 'Nur Aisyah', ic: 'No', rate: 16, confirmed: false, onDuty: false, actualStart: '', actualEnd: '' }],
    photos: [],
    billing: 'Not Billed',
    invoice: '',
    billedDate: '',
  },
  {
    id: 'PN-2043',
    customer: 'Sentinel Events Pte Ltd',
    location: 'MBS Convention Hall 601',
    date: '2026-07-10',
    start: '18:00',
    end: '23:00',
    required: 4,
    status: 'Confirmed',
    posted: true,
    description: 'Access control at trade-expo registration counters.',
    instructions: 'Report to Hall 601 concierge.',
    officers: [
      { oid: 'OF-01', name: 'Rajesh Kumar', ic: 'Yes', rate: 16, confirmed: true, onDuty: false, actualStart: '', actualEnd: '' },
      { oid: 'OF-03', name: 'Tan Wei Ming', ic: 'Yes', rate: 18, confirmed: true, onDuty: false, actualStart: '', actualEnd: '' },
      { oid: 'OF-05', name: 'Lim Jun Hao', ic: 'Yes', rate: 17, confirmed: true, onDuty: false, actualStart: '', actualEnd: '' },
      { oid: 'OF-08', name: 'Deepak Raj', ic: 'Yes', rate: 19, confirmed: true, onDuty: false, actualStart: '', actualEnd: '' },
    ],
    photos: [],
    billing: 'Not Billed',
    invoice: '',
    billedDate: '',
  },
  {
    id: 'PN-2044',
    customer: 'VivoCity Mall Mgmt',
    location: 'VivoCity - Level 1 Main Entrance',
    date: '2026-07-07',
    start: '10:00',
    end: '22:00',
    required: 2,
    status: 'Completed',
    posted: true,
    description: 'Mall entrance bag-check and crowd flow.',
    instructions: 'Standard mall SOP.',
    officers: [
      { oid: 'OF-03', name: 'Tan Wei Ming', ic: 'Yes', rate: 18, confirmed: true, onDuty: true, actualStart: '10:00', actualEnd: '22:00' },
      { oid: 'OF-05', name: 'Lim Jun Hao', ic: 'Yes', rate: 17, confirmed: true, onDuty: true, actualStart: '10:05', actualEnd: '22:10' },
    ],
    photos: [
      { time: '11:00', status: 'received', by: 'Tan Wei Ming', at: '11:02' },
      { time: '12:00', status: 'received', by: 'Lim Jun Hao', at: '12:01' },
      { time: '13:00', status: 'received', by: 'Tan Wei Ming', at: '13:03' },
    ],
    billing: 'Not Billed',
    invoice: '',
    billedDate: '',
  },
  {
    id: 'PN-2045',
    customer: 'Marina Bay Sands',
    location: 'MBS Tower 3 - Lobby',
    date: '2026-07-06',
    start: '20:00',
    end: '04:00',
    required: 3,
    status: 'Completed',
    posted: true,
    description: 'Overnight lobby and lift-lobby security.',
    instructions: 'Night shift. Handover log at concierge.',
    officers: [
      { oid: 'OF-01', name: 'Rajesh Kumar', ic: 'Yes', rate: 16, confirmed: true, onDuty: true, actualStart: '20:00', actualEnd: '04:00' },
      { oid: 'OF-02', name: 'Muhammad Faizal', ic: 'Yes', rate: 15, confirmed: true, onDuty: true, actualStart: '20:00', actualEnd: '04:05' },
      { oid: 'OF-08', name: 'Deepak Raj', ic: 'Yes', rate: 19, confirmed: true, onDuty: true, actualStart: '20:10', actualEnd: '04:00' },
    ],
    photos: [],
    billing: 'Billed',
    invoice: 'INV-2026-0455',
    billedDate: '2026-07-07',
  },
  {
    id: 'PN-2046',
    customer: 'Raffles City',
    location: 'Raffles City Shopping Centre',
    date: '2026-07-11',
    start: '12:00',
    end: '21:00',
    required: 2,
    status: 'Draft',
    posted: false,
    description: 'Weekend concourse patrol.',
    instructions: '',
    officers: [],
    photos: [],
    billing: 'Not Billed',
    invoice: '',
    billedDate: '',
  },
];

export const requests: RequestRow[] = [
  { id: 'RQ-118', customer: 'Sentinel Events Pte Ltd', method: 'WhatsApp', reqDate: '2026-07-06', location: 'Marina Bay Sands', jobDate: '2026-07-08', start: '18:00', end: '23:00', officers: 4, notes: 'Corporate gala, black tie', status: 'Converted' },
  { id: 'RQ-119', customer: 'Changi Airport Group', method: 'Email', reqDate: '2026-07-06', location: 'Jewel Changi', jobDate: '2026-07-08', start: '08:00', end: '20:00', officers: 6, notes: 'School holiday coverage', status: 'Converted' },
  { id: 'RQ-120', customer: 'OCBC Centre', method: 'WhatsApp', reqDate: '2026-07-07', location: 'OCBC Centre', jobDate: '2026-07-12', start: '09:00', end: '18:00', officers: 3, notes: 'Lobby access control', status: 'New' },
  { id: 'RQ-121', customer: 'Great World City', method: 'WhatsApp', reqDate: '2026-07-07', location: 'Great World City', jobDate: '2026-07-13', start: '10:00', end: '22:00', officers: 2, notes: 'Mall event weekend', status: 'New' },
];

export const payments: Payment[] = [
  { id: 'PY-01', officer: 'Tan Wei Ming', jobId: 'PN-2044', jobDate: '2026-07-07', hours: 12, rate: 18, status: 'Pending', paidDate: '' },
  { id: 'PY-02', officer: 'Lim Jun Hao', jobId: 'PN-2044', jobDate: '2026-07-07', hours: 12.08, rate: 17, status: 'Pending', paidDate: '' },
  { id: 'PY-03', officer: 'Rajesh Kumar', jobId: 'PN-2045', jobDate: '2026-07-06', hours: 8, rate: 16, status: 'Paid', paidDate: '2026-07-07' },
  { id: 'PY-04', officer: 'Muhammad Faizal', jobId: 'PN-2045', jobDate: '2026-07-06', hours: 8.08, rate: 15, status: 'Paid', paidDate: '2026-07-07' },
  { id: 'PY-05', officer: 'Deepak Raj', jobId: 'PN-2045', jobDate: '2026-07-06', hours: 7.83, rate: 19, status: 'Paid', paidDate: '2026-07-07' },
];

export const routeMeta: Record<RouteKey, { crumb: string; title: string }> = {
  dashboard: { crumb: 'Overview', title: 'Dashboard' },
  requests: { crumb: 'Operations', title: 'Job Requests' },
  jobs: { crumb: 'Operations', title: 'Jobs' },
  jobDetail: { crumb: 'Operations / Jobs', title: 'Job detail' },
  shift: { crumb: 'Operations', title: 'Shift Monitoring' },
  officers: { crumb: 'People', title: 'Officer Management' },
  summary: { crumb: 'Finance', title: 'Completed Job Summary' },
  payments: { crumb: 'Finance', title: 'Officer Payment' },
  billing: { crumb: 'Finance', title: 'Customer Billing' },
  reports: { crumb: 'Insights', title: 'Reports' },
};

export const statusRank: Record<JobStatus, number> = {
  'Waiting for Officers': 0,
  Confirmed: 1,
  Ongoing: 2,
  Completed: 3,
  Draft: 4,
  Cancelled: 5,
};

export const nav: NavGroup[] = [
  { section: 'OPERATIONS', items: [{ key: 'dashboard', href: '/', label: 'Dashboard', icon: LayoutDashboard }, { key: 'jobs', href: '/jobs', label: 'Jobs', icon: BriefcaseBusiness }, { key: 'shift', href: '/shift', label: 'Shift Monitoring', icon: CircleDot }, { key: 'requests', href: '/requests', label: 'Job Requests', icon: ClipboardCheck }] },
  { section: 'PEOPLE', items: [{ key: 'officers', href: '/officers', label: 'Officer Management', icon: Users }] },
  { section: 'FINANCE', items: [{ key: 'summary', href: '/finance/summary', label: 'Completed Job Summary', icon: Check }, { key: 'payments', href: '/finance/payments', label: 'Officer Payment', icon: CreditCard }, { key: 'billing', href: '/finance/billing', label: 'Customer Billing', icon: FileText }] },
  { section: 'INSIGHTS', items: [{ key: 'reports', href: '/reports', label: 'Reports', icon: FileBarChart }] },
];
