import type { Job, Officer, Payment } from './types';

export const officersSeed: Officer[] = [
  { id: 'OF-01', name: 'Rajesh Kumar', phone: '+65 8123 4567', status: 'Active', ic: true, rate: 16, jobsCount: 34 },
  { id: 'OF-02', name: 'Muhammad Faizal', phone: '+65 9231 7788', status: 'Active', ic: true, rate: 15, jobsCount: 22 },
  { id: 'OF-03', name: 'Tan Wei Ming', phone: '+65 8890 2211', status: 'Active', ic: true, rate: 18, jobsCount: 41 },
  { id: 'OF-04', name: 'Arjun Nair', phone: '+65 9022 5610', status: 'New', ic: false, rate: 14, jobsCount: 0 },
  { id: 'OF-05', name: 'Lim Jun Hao', phone: '+65 8455 9832', status: 'Active', ic: true, rate: 17, jobsCount: 15 },
  { id: 'OF-06', name: 'Siti Nurhaliza', phone: '+65 9188 3345', status: 'Inactive', ic: true, rate: 16, jobsCount: 9 },
  { id: 'OF-07', name: 'Kwok Ah Seng', phone: '+65 8321 0099', status: 'Blocked', ic: true, rate: 15, jobsCount: 6 },
  { id: 'OF-08', name: 'Deepak Raj', phone: '+65 9077 4521', status: 'Active', ic: true, rate: 19, jobsCount: 28 },
];

export const jobsSeed: Job[] = [
  {
    id: 'PN-2041',
    customer: 'Sentinel Events Pte Ltd',
    location: 'Marina Bay Sands – Expo Hall B',
    date: '2026-07-08',
    start: '18:00',
    end: '23:00',
    required: 4,
    status: 'Job ongoing',
    posted: true,
    description: 'Crowd control and access management for a 600-pax corporate gala dinner.',
    instructions: 'Black-tie event. Report to Ops Manager Mr. Chua at Loading Bay 2 by 17:30. No mobile phones on the floor.',
    cancelReason: '',
    officers: [
      { oid: 'OF-01', name: 'Rajesh Kumar', ic: true, rate: 16, confirmed: true, onDuty: true, actualStart: '18:02', actualEnd: '' },
      { oid: 'OF-02', name: 'Muhammad Faizal', ic: true, rate: 15, confirmed: true, onDuty: true, actualStart: '18:00', actualEnd: '' },
      { oid: 'OF-03', name: 'Tan Wei Ming', ic: true, rate: 18, confirmed: true, onDuty: false, actualStart: '', actualEnd: '' },
    ],
    photos: [
      { time: '18:00', status: 'received', by: 'Rajesh Kumar', at: '18:05' },
      { time: '19:00', status: 'received', by: 'Muhammad Faizal', at: '19:03' },
      { time: '20:00', status: 'missing', by: '', at: '' },
      { time: '21:00', status: 'upcoming', by: '', at: '' },
      { time: '22:00', status: 'upcoming', by: '', at: '' },
    ],
    billing: 'Not Billed',
    invoice: '',
    billedDate: '',
  },
  {
    id: 'PN-2042',
    customer: 'Changi Airport Group',
    location: 'Jewel Changi – Level 1 Atrium',
    date: '2026-07-08',
    start: '08:00',
    end: '20:00',
    required: 6,
    status: 'Posted/Waiting',
    posted: true,
    description: 'Retail concourse patrol and lost-and-found support during school holidays.',
    instructions: 'Uniform: Class A. Coordinate with Jewel Ops room B1-22.',
    cancelReason: '',
    officers: [
      { oid: 'OF-05', name: 'Lim Jun Hao', ic: true, rate: 17, confirmed: true, onDuty: false, actualStart: '', actualEnd: '' },
      { oid: 'OF-08', name: 'Deepak Raj', ic: true, rate: 19, confirmed: false, onDuty: false, actualStart: '', actualEnd: '' },
    ],
    photos: [],
    billing: 'Not Billed',
    invoice: '',
    billedDate: '',
  },
  {
    id: 'PN-2050',
    customer: 'Resorts World Sentosa',
    location: 'RWS – Festive Grand Theatre',
    date: '2026-07-08',
    start: '17:00',
    end: '23:30',
    required: 5,
    status: 'Officers confirmed',
    posted: true,
    description: 'Ticketed show — foyer and hall access control.',
    instructions: 'Report to backstage security desk by 16:30.',
    cancelReason: '',
    officers: [
      { oid: 'OF-05', name: 'Lim Jun Hao', ic: true, rate: 17, confirmed: true, onDuty: false, actualStart: '', actualEnd: '' },
      { oid: 'OF-08', name: 'Deepak Raj', ic: true, rate: 19, confirmed: true, onDuty: false, actualStart: '', actualEnd: '' },
      { oid: 'OF-01', name: 'Rajesh Kumar', ic: true, rate: 16, confirmed: true, onDuty: false, actualStart: '', actualEnd: '' },
      { oid: 'OF-03', name: 'Tan Wei Ming', ic: true, rate: 18, confirmed: true, onDuty: false, actualStart: '', actualEnd: '' },
      { oid: 'OF-02', name: 'Muhammad Faizal', ic: true, rate: 15, confirmed: true, onDuty: false, actualStart: '', actualEnd: '' },
    ],
    photos: [],
    billing: 'Not Billed',
    invoice: '',
    billedDate: '',
  },
  {
    id: 'PN-2044',
    customer: 'VivoCity Mall Mgmt',
    location: 'VivoCity – Level 1 Main Entrance',
    date: '2026-07-07',
    start: '10:00',
    end: '22:00',
    required: 2,
    status: 'Completed',
    posted: true,
    description: 'Mall entrance bag-check and crowd flow.',
    instructions: 'Standard mall SOP.',
    cancelReason: '',
    officers: [
      { oid: 'OF-03', name: 'Tan Wei Ming', ic: true, rate: 18, confirmed: true, onDuty: true, actualStart: '10:00', actualEnd: '22:00' },
      { oid: 'OF-05', name: 'Lim Jun Hao', ic: true, rate: 17, confirmed: true, onDuty: true, actualStart: '10:05', actualEnd: '22:10' },
    ],
    photos: [
      { time: '11:00', status: 'received', by: 'Tan Wei Ming', at: '11:02' },
      { time: '12:00', status: 'received', by: 'Tan Wei Ming', at: '12:01' },
      { time: '13:00', status: 'received', by: 'Tan Wei Ming', at: '13:03' },
      { time: '14:00', status: 'received', by: 'Tan Wei Ming', at: '14:00' },
      { time: '15:00', status: 'received', by: 'Tan Wei Ming', at: '15:04' },
      { time: '16:00', status: 'received', by: 'Tan Wei Ming', at: '16:01' },
      { time: '17:00', status: 'received', by: 'Tan Wei Ming', at: '17:02' },
      { time: '12:00', status: 'received', by: 'Lim Jun Hao', at: '12:01' },
    ],
    billing: 'Not Billed',
    invoice: '',
    billedDate: '',
  },
  {
    id: 'PN-2045',
    customer: 'Marina Bay Sands',
    location: 'MBS Tower 3 – Lobby',
    date: '2026-07-06',
    start: '20:00',
    end: '04:00',
    required: 3,
    status: 'Completed',
    posted: true,
    description: 'Overnight lobby and lift-lobby security.',
    instructions: 'Night shift. Handover log at concierge.',
    cancelReason: '',
    officers: [
      { oid: 'OF-01', name: 'Rajesh Kumar', ic: true, rate: 16, confirmed: true, onDuty: true, actualStart: '20:00', actualEnd: '04:00' },
      { oid: 'OF-02', name: 'Muhammad Faizal', ic: true, rate: 15, confirmed: true, onDuty: true, actualStart: '20:00', actualEnd: '04:05' },
      { oid: 'OF-08', name: 'Deepak Raj', ic: true, rate: 19, confirmed: true, onDuty: true, actualStart: '20:10', actualEnd: '04:00' },
    ],
    photos: [],
    billing: 'Billed',
    invoice: 'INV-2026-0455',
    billedDate: '2026-07-07',
  },
  {
    id: 'PN-2046',
    customer: 'Raffles City',
    location: 'Raffles City Shopping Centre',
    date: '2026-07-11',
    start: '12:00',
    end: '21:00',
    required: 2,
    status: 'Draft Created',
    posted: false,
    description: 'Weekend concourse patrol.',
    instructions: '',
    cancelReason: '',
    officers: [],
    photos: [],
    billing: 'Not Billed',
    invoice: '',
    billedDate: '',
  },
  {
    id: 'PN-2051',
    customer: 'ION Orchard',
    location: 'ION Orchard – Level 1 Concierge',
    date: '2026-07-08',
    start: '11:00',
    end: '21:00',
    required: 3,
    status: 'Posted/Waiting',
    posted: true,
    description: 'Weekend mall concourse patrol and bag-check.',
    instructions: 'Class A uniform. Report to mall command centre B2.',
    cancelReason: '',
    officers: [{ oid: 'OF-06', name: 'Siti Nurhaliza', ic: true, rate: 16, confirmed: false, onDuty: false, actualStart: '', actualEnd: '' }],
    photos: [],
    billing: 'Not Billed',
    invoice: '',
    billedDate: '',
  },
  {
    id: 'PN-2052',
    customer: 'Capitaland',
    location: 'Raffles City – Atrium',
    date: '2026-07-08',
    start: '09:00',
    end: '18:00',
    required: 2,
    status: 'Posted/Waiting',
    posted: true,
    description: 'Roadshow perimeter and queue management.',
    instructions: 'Setup from 08:30 with event crew.',
    cancelReason: '',
    officers: [],
    photos: [],
    billing: 'Not Billed',
    invoice: '',
    billedDate: '',
  },
  {
    id: 'PN-2043',
    customer: 'Suntec Convention',
    location: 'Suntec City – Hall 601',
    date: '2026-07-10',
    start: '09:00',
    end: '18:00',
    required: 3,
    status: 'Posted/Waiting',
    posted: true,
    description: 'Access control at trade-expo registration counters.',
    instructions: 'Report to Hall 601 concierge.',
    cancelReason: '',
    officers: [],
    photos: [],
    billing: 'Not Billed',
    invoice: '',
    billedDate: '',
  },
  {
    id: 'PN-2047',
    customer: 'DBS Marina',
    location: 'DBS Asia Central',
    date: '2026-07-09',
    start: '08:00',
    end: '17:00',
    required: 4,
    status: 'Officers confirmed',
    posted: true,
    description: 'Corporate HQ lobby and turnstile management.',
    instructions: 'Corporate attire. Photo ID at security desk.',
    cancelReason: '',
    officers: [
      { oid: 'OF-01', name: 'Rajesh Kumar', ic: true, rate: 16, confirmed: true, onDuty: false, actualStart: '', actualEnd: '' },
      { oid: 'OF-03', name: 'Tan Wei Ming', ic: true, rate: 18, confirmed: true, onDuty: false, actualStart: '', actualEnd: '' },
      { oid: 'OF-05', name: 'Lim Jun Hao', ic: true, rate: 17, confirmed: true, onDuty: false, actualStart: '', actualEnd: '' },
      { oid: 'OF-08', name: 'Deepak Raj', ic: true, rate: 19, confirmed: true, onDuty: false, actualStart: '', actualEnd: '' },
    ],
    photos: [],
    billing: 'Not Billed',
    invoice: '',
    billedDate: '',
  },
  {
    id: 'PN-2048',
    customer: 'NParks Event',
    location: 'Gardens by the Bay',
    date: '2026-07-04',
    start: '16:00',
    end: '23:00',
    required: 5,
    status: 'Cancelled',
    posted: true,
    description: 'Outdoor concert perimeter security.',
    instructions: '',
    cancelReason: 'Client postponed the event due to weather.',
    officers: [],
    photos: [],
    billing: 'Not Billed',
    invoice: '',
    billedDate: '',
  },
];

export const paymentsSeed: Payment[] = [
  { id: 'PY-01', officer: 'Tan Wei Ming', jobId: 'PN-2044', jobDate: '2026-07-07', hours: 12, rate: 18, status: 'Pending', paidDate: '' },
  { id: 'PY-02', officer: 'Lim Jun Hao', jobId: 'PN-2044', jobDate: '2026-07-07', hours: 12.08, rate: 17, status: 'Pending', paidDate: '' },
  { id: 'PY-03', officer: 'Rajesh Kumar', jobId: 'PN-2045', jobDate: '2026-07-06', hours: 8, rate: 16, status: 'Paid', paidDate: '2026-07-07' },
  { id: 'PY-04', officer: 'Muhammad Faizal', jobId: 'PN-2045', jobDate: '2026-07-06', hours: 8.08, rate: 15, status: 'Paid', paidDate: '2026-07-07' },
  { id: 'PY-05', officer: 'Deepak Raj', jobId: 'PN-2045', jobDate: '2026-07-06', hours: 7.83, rate: 19, status: 'Paid', paidDate: '2026-07-07' },
  { id: 'PY-06', officer: 'Tan Wei Ming', jobId: 'PN-2039', jobDate: '2026-07-02', hours: 9, rate: 18, status: 'Paid', paidDate: '2026-07-03' },
  { id: 'PY-07', officer: 'Tan Wei Ming', jobId: 'PN-2035', jobDate: '2026-06-27', hours: 8, rate: 18, status: 'Paid', paidDate: '2026-06-28' },
  { id: 'PY-08', officer: 'Tan Wei Ming', jobId: 'PN-2030', jobDate: '2026-06-20', hours: 10, rate: 17, status: 'Paid', paidDate: '2026-06-21' },
  { id: 'PY-09', officer: 'Tan Wei Ming', jobId: 'PN-2026', jobDate: '2026-06-14', hours: 12, rate: 17, status: 'Paid', paidDate: '2026-06-15' },
];
